# - name: "Install LLVM repository"
#     apt_repository:
#       repo: deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main
#         state: present
#         filename: 'llvm.list'

# - name: "Install LLVM src repository"
#     apt_repository:
#       repo: deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main
#         state: present
#         filename: 'llvm.list'

# - name: "Add LLVM key"
#   apt_key:
#     url: https://apt.llvm.org/llvm-snapshot.gpg.key
#     state: present

- name: "Install LLVM 11"
  package:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    libllvm11
    llvm-11
    llvm-11-dev
    llvm-11-doc
    llvm-11-examples
    llvm-11-runtime
    clang-11
    clang-tools-11
    clang-11-doc
    libclang-common-11-dev
    libclang-11-dev
    libclang1-11
    clang-format-11
    clangd-11
