- name: Set up local workstation
  hosts: local
  roles:
    - role: zsh
  #   - role: ccls
  #   - role: cmake
  #   - role: utils
  #   - role: emacs
  #   - role: doom
  #   - role: dotfiles
  #   - role: llvm11
  vars:
    home_user: "{{ lookup('env', 'USER') }}"
    home_dir: "{{ lookup('env', 'HOME') }}"
